### ISSUE TITLE
Stanley Vertical Cross Track Problem

### ISSUE THREAD

**Issue by aditya-penumarti** [av-mae-uf/eml4930_gps_nav#4]
The Vehicle having the cross track error that is a line that is 90 degrees from the x axis of the vehicle. The vehicle tries to compensate highly on the cross track error, which causes high instability. Need to drag the pose list to start at the current vehicle pose might solve this issue. This issue is only present with the Stanley Controller

**Comment by aditya-penumarti** [comment]
> The Vehicle having the cross track error that is a line that is 90 degrees from the x axis of the vehicle. The vehicle tries to compensate highly on the cross track error, which causes high instability. Need to drag the pose list to start at the current vehicle pose might solve this issue. This issue is only present with the Stanley Controller

The closest point not publishing a pose was causing some of these issues, a true Stanley should still be able to operate with errors. Would still be better to extend the path back to the vehicle, or ensure the car starts at the path starting point.

**Comment by patrick-neal** [comment]
Was this resolved?

**Comment by aditya-penumarti** [comment]
Yep it was resolved with the updated code that Dr.Crane pushed
________________________________
