### ISSUE TITLE
Pose List Copy to Share

### ISSUE THREAD

**Issue by aditya-penumarti** [av-mae-uf/eml4930_gps_nav#5]
The pose list for the students need to be easily copied over to a share file that the gps_nav will interface with. Right now the pose list is being put into gps_nav to solve this issue. Maybe a way to have the data folder in their package that transfers it to a share folder that it could access.

**Comment by patrick-neal** [comment]
They can use the launch file to specify any file location they want for the pose list file.

**Comment by aditya-penumarti** [comment]
> They can use the launch file to specify any file location they want for the pose list file.

Yep realized that after I made this I'll close it out.
